# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.custom", "45a57656-9d52-174d-9efe-2b062b5e0678");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1403112492);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.user-agent-updates-timer", 0);
user_pref("b2g.wifi.allow_unsafe_wpa_eap", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.homescreenURL", "app://system.gaiamobile.org/index.html");
user_pref("browser.manifestURL", "app://system.gaiamobile.org/manifest.webapp");
user_pref("consoleservice.enabled", true);
user_pref("device.storage.writable.name", "sdcard");
user_pref("devtools.debugger.forbid-certified-apps", false);
user_pref("devtools.debugger.prompt-connection", false);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.debugger.unix-domain-socket", "59217");
user_pref("devtools.eventlooplag.threshold", 100);
user_pref("dom.mms.requestStatusReport", false);
user_pref("dom.mms.retrieval_mode", "automatic-home");
user_pref("dom.mms.version", 17);
user_pref("dom.mozApps.maxLocalId", 1001);
user_pref("dom.mozApps.used", true);
user_pref("dom.sms.requestStatusReport", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.lastAppVersion", "32.0a1");
user_pref("extensions.lastPlatformVersion", "32.0a1");
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140506040204");
user_pref("gecko.mstone", "32.0a1");
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.options.discardSystemSource", false);
user_pref("layers.composer2d.enabled", false);
user_pref("layers.simple-tiles", false);
user_pref("layout.css.dpi", 135);
user_pref("marionette.contentListener", false);
user_pref("network.dns.localDomains", "gaiamobile.org,bluetooth.gaiamobile.org,bookmark.gaiamobile.org,browser.gaiamobile.org,calendar.gaiamobile.org,callscreen.gaiamobile.org,camera.gaiamobile.org,clock.gaiamobile.org,communications.gaiamobile.org,costcontrol.gaiamobile.org,email.gaiamobile.org,emergency-call.gaiamobile.org,findmydevice.gaiamobile.org,fl.gaiamobile.org,fm.gaiamobile.org,gallery.gaiamobile.org,homescreen.gaiamobile.org,keyboard.gaiamobile.org,marketplace.firefox.com.gaiamobile.org,music.gaiamobile.org,operatorvariant.gaiamobile.org,pdfjs.gaiamobile.org,ringtones.gaiamobile.org,search.gaiamobile.org,setringtone.gaiamobile.org,settings.gaiamobile.org,sms.gaiamobile.org,system.gaiamobile.org,video.gaiamobile.org,wallpaper.gaiamobile.org,wappush.gaiamobile.org");
user_pref("network.http.max-connections-per-server", 15);
user_pref("privacy.donottrackheader.value", -1);
user_pref("ril.debugging.enabled", false);
user_pref("ril.mms.mmsc", "");
user_pref("ril.mms.mmsport", 0);
user_pref("ril.mms.mmsproxy", "");
user_pref("ril.radio.disabled", false);
user_pref("toolkit.telemetry.previousBuildID", "20140506040204");
