# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1403111726);
user_pref("app.update.lastUpdateTime.background-update-timer", 1403111366);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1403111846);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1403111246);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1403111606);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1403111486);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140617101048");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 2849);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20140617101048");
user_pref("browser.startup.homepage_override.mstone", "33.0a1");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"e10s-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"webrtc-status-button\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-call-button\",\"social-share-button\",\"action-button--jid1-zojfttqy0m8j9gjetpack-ui-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"action-button--jid1-zojfttqy0m8j9gjetpack-ui-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\"],\"newElementCount\":0}");
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1403197525892");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1403111125891");
user_pref("datareporting.sessions.current.activeTicks", 176);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2718);
user_pref("datareporting.sessions.current.main", 55);
user_pref("datareporting.sessions.current.sessionRestored", 2932);
user_pref("datareporting.sessions.current.startTime", "1403111125349");
user_pref("datareporting.sessions.current.totalTime", 1882);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.command-button-eyedropper.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.errorconsole.enabled", true);
user_pref("devtools.netmonitor.enabled", false);
user_pref("devtools.selfxss.count", 10);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_OPTIONS_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_WEBAUDIOEDITOR_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_CUSTOM_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_JSPROFILER_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_STYLEEDITOR_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"33.0a1\",\"DEVTOOLS_DEVELOPERTOOLBAR_OPENED_PER_USER_FLAG\":\"33.0a1\"}");
user_pref("devtools.toolbar.visible", true);
user_pref("devtools.toolbox.footer.height", 283);
user_pref("devtools.toolbox.selectedTool", "styleeditor");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("devtools.webaudioeditor.enabled", true);
user_pref("devtools.webide.addonsURL_cache", "{\n  \"stable\": [\"1.3\", \"1.4\"],\n  \"unstable\": [\"2.0\"]\n}\n");
user_pref("devtools.webide.autoinstallADBHelper", false);
user_pref("devtools.webide.enabled", true);
user_pref("devtools.webide.lastprojectlocation", "/Users/dcamp/git/justfortesting");
user_pref("devtools.webide.showProjectEditor", false);
user_pref("devtools.webide.templatesURL_cache", "[\n  {\n    \"file\": \"http://people.mozilla.org/~prouget/webidetemplates/template.zip\",\n    \"icon\": \"http://people.mozilla.org/~prouget/webidetemplates/icon.png\",\n    \"name\": \"temporary template\",\n    \"description\": \"just for testing. More to come.\"\n  }\n]\n");
user_pref("dom.mozApps.used", true);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"jid1-ZojFTTqy0M8J9g@jetpack\":{\"version\":\"0.0.1\",\"type\":\"extension\",\"descriptor\":\"/Users/dcamp/git/fxdt-adapters/demo_profile/extensions/jid1-ZojFTTqy0M8J9g@jetpack.xpi\"},\"adbhelper@mozilla.org\":{\"version\":\"0.2.3\",\"type\":\"extension\",\"descriptor\":\"/Users/dcamp/git/fxdt-adapters/demo_profile/extensions/adbhelper@mozilla.org\"},\"fxos_2_0_simulator@mozilla.org\":{\"version\":\"2.0.20140506\",\"type\":\"extension\",\"descriptor\":\"/Users/dcamp/git/fxdt-adapters/demo_profile/extensions/fxos_2_0_simulator@mozilla.org\"}}");
user_pref("extensions.checkCompatibility.33.0a", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.0a1");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Users/dcamp/moz/fx/obj/dist/NightlyDebug.app/Contents/MacOS/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1403109209000,\"rdfTime\":1403109209000}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-ZojFTTqy0M8J9g@jetpack\":{\"descriptor\":\"/Users/dcamp/git/fxdt-adapters/demo_profile/extensions/jid1-ZojFTTqy0M8J9g@jetpack.xpi\",\"mtime\":1403111125000}}}]");
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "33.0a1");
user_pref("extensions.lastPlatformVersion", "33.0a1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sdk.console.logLevel", "info");
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("gecko.buildID", "20140617101048");
user_pref("gecko.mstone", "33.0a1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("toolkit.startup.last_success", 1403111125);
user_pref("toolkit.telemetry.previousBuildID", "20140618093206");
user_pref("urlclassifier.updateinterval", 172800);
